### PR TITLE
Remove query builder package

### PR DESCRIPTION
**Pull request by quolpr**

### CODE REVIEW

**Comment by astahmer** [comment]
hey, lots of changes here again, i'll wait till this is merged & published (like the fluent API PR changes) to get up to date but I wanted to tell you that I managed to get auto generated migrations / auto typed kysely query builder / full typesafe hooks (useRunQuery / useQuery)

so I don't mean to be rude or anything but I think the query builder space is mostly solved with kysely ?

the repo is private i'll open it soon but it basically looks like this:
Screenshot 2022-10-17 at 00 36 25
Screenshot 2022-10-17 at 00 37 38

**Comment by quolpr** [comment]
@astahmer hmm, that sounds interesting.  I looked at kysely, and I liked the idea. In fact, I tried to build the type safe version of boono — but it is pretty hard if you want to support complex queries with CTE, for example. I wanted to have a query builder that will support all the things that SQLite can offer.

As another idea, I was thinking about to use SQLite to parse SQL queries and generate types. But unfortunately, SQLite can provide you type information only when query is executed 😞

But yeah, maybe it will be a good idea to build an adapter to kysely 🤔

**Comment by quolpr** [comment]
As for the changes — yeah, they are a lot. I am trying to find the simplest and the best API that will make DX very comfortable. 

It is possible that I will change my mind a lot of time before 1.0 release 😅

**Comment by quolpr** [comment]
Also, one thing that I don't like about Kysely (and in Knex btw too) — the query builder is tightly coupled with the query executor. If Kysely could provide just query builder and nothing also, then integration with Kikko will look natural 🙂 

Maybe it is a good idea to create an issue at Kysely repo 😅

**Comment by astahmer** [comment]
> but it is pretty hard if you want to support complex queries with CTE, for example.

oh ok, I don't know much about kysely or even SQL tbh, it seemed complete for a sql novice point of view

>  I wanted to have a query builder that will support all the things that SQLite can offer.

kinda related but now so much: I stumbled upon this feature recently and wondered if that works atm using kikko or is planned ?
https://www.sqlite.org/fts5.html

> But yeah, maybe it will be a good idea to build an adapter to kysely 🤔
> Also, one thing that I don't like about Kysely (and in Knex btw too) — the query builder is tightly coupled with the query executor. If Kysely could provide just query builder and nothing also, then integration with Kikko will look natural 🙂


yeah that's [what I did here](https://github.com/astahmer/vite-kikko-models/blob/5066fe8ac1218221539a89da433c3c996e175bc3/src/lib/kyselyToKikkoISql.ts), I just opened the repo, it's still a bip wip but the basic demo should works
it's not so tightly coupled since we can use the AST-like output (using `.toOperationNode()`)

no problem with the big changes, this is early so ofc it's fine, take your time I'm just having fun with what's already available !
btw thanks again for your work on this, this makes everything so much easier !

**Pull request merged**
